### ISSUE TITLE
Launch never finishes, remains in progress

### ISSUE THREAD

**Issue by zvpanchal** [BorisOsipov/wdio-reportportal-service#33]
Problem: Report Portal launches remain "In Progress" even after the test suite completes.

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/98423416/156476063-a002bcd7-d8be-4294-a8a2-af05beffc45a.png">

Below is my package.json
```
"dependencies": {
        "@wdio/allure-reporter": "^7.12.5",
        "@wdio/appium-service": "^7.12.5",
        "@wdio/browserstack-service": "^7.12.5",
        "@wdio/cli": "^7.12.6",
        "@wdio/local-runner": "^7.12.5",
        "@wdio/mocha-framework": "^7.12.5",
        "@wdio/spec-reporter": "^7.12.5",
        "@wdio/sync": "^7.12.5",
        "wdio-reportportal-reporter": "^7.4.1",
        "wdio-reportportal-service": "^7.3.1",
        "assert": "^2.0.0",
        "aws-sdk": "^2.972.0",
        "config": "^1.28.1",
        "eslint": "^7.32.0",
        "eslint-config-airbnb-base": "^14.2.1",
        "eslint-plugin-import": "^2.24.1",
        "eslint-plugin-wdio": "^7.0.0",
        "fs": "0.0.1-security",
        "mocha": "^6.2.3",
        "prettier": "^1.19.1",
        "request": "^2.88.2",
        "request-promise": "^4.2.6",
        "wd": "^1.14.0",
        "webdriverio": "^7.12.5",
        "xml2js": "^0.4.23"
    },
```

Below is my config file
```
services: [
    [
      'appium',
    ],
    [
      'browserstack', {
        browserstackLocal: false,
      },
    ],
    [
      'RpService', {
      },
    ],
],
```

**Comment by BorisOsipov** [comment]
@zvpanchal Please read docs carefully.
use:
```
const RpService = require('wdio-reportportal-service');

exports.config = {
  // ...
  services: [[RpService, {}]],
  // ...
}
```
not 
```
    [
      'RpService', {
      },
    ],
```


Also

```
    [
      'reportportal', {
      },
    ],
```
should work, but I haven't tried

**Comment by zvpanchal** [comment]
Hi @BorisOsipov - Thanks for your reply.

I do have 2 projects using `wdio-reportportal-service`; (1) Web Automation, and (2) Mobile Automation.
For Web Automation - `[[RpService, {configParams}]]` worked. (_`[[RpService, {}]]` did not work as expected_)

For Mobile Automation where I also need to use appium service in the array, I did try using `[[RpService, {}]]`, `[[RpService, { configParams }]]` or `[[reportportal, {configParams}]]`. None of these options worked for my mobile test automation when I have appium in the services list.

**Comment by BorisOsipov** [comment]
@zvpanchal could not help without reproducible example. please create simple github repo that I can clone and repro the issue.

**Comment by zvpanchal** [comment]
@BorisOsipov - Sure, I will.

I did some trial and error, and found that if I remove `appium` from the services array, then `wdio-reportportal-service` works as expected (i.e. it completes the launch on report portal after finishing all the tests).

As soon as I add `appium` in the array, RpService does not work as intended... so something to look at..

 I will work on getting a repo up and running for you to reproduce
