### ISSUE TITLE
Creates a launch per test suite instead of one launch including all suites for given session

### ISSUE THREAD

**Issue by zvpanchal** [BorisOsipov/wdio-reportportal-service#34]
**Problem:**  When we run all test suites from the WebdriverIO in one session along with `appium` service, it creates 1 launch per test spec file on the Report Portal.

**Expected outcome:** There should only be 1 launch per test execution session, and it should include all test specs that is part of the test execution.

**Comment by BorisOsipov** [comment]
It is the same issue as in https://github.com/BorisOsipov/wdio-reportportal-service/issues/34 let's continue convo in #34
